### ISSUE TITLE
Cannot open: https://beta.tableau.com/linux_files/tableau-server-10.5-beta5.x86_64.rpm. Skipping.

### ISSUE THREAD

**Issue by gclsoft** [tfoldi/tableau-server-beta-docker#1]
Loaded plugins: fastestmirror, ovl
Cannot open: https://beta.tableau.com/linux_files/tableau-server-automated-installer-10.5-beta5.noarch.rpm. Skipping.
Cannot open: https://beta.tableau.com/linux_files/tableau-server-10.5-beta5.x86_64.rpm. Skipping.
Cannot open: https://beta.tableau.com/linux_driver/tableau-postgresql-odbc-9.5.3-1.x86_64.rpm. Skipping.
Error: Nothing to do

**Comment by gclsoft** [comment]
Complete!
Loaded plugins: fastestmirror, ovl
Cannot open: https://beta.tableau.com/linux_files/tableau-server-automated-installer-10.5-beta5.noarch.rpm. Skipping.
Cannot open: https://beta.tableau.com/linux_files/tableau-server-10.5-beta5.x86_64.rpm. Skipping.
Cannot open: https://beta.tableau.com/linux_driver/tableau-postgresql-odbc-9.5.3-1.x86_64.rpm. Skipping.
Error: Nothing to do
The command '/bin/sh -c rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm &&     yum install -y iproute curl sudo vim &&     adduser tsm &&     (echo tsm:tsm | chpasswd) &&     (echo 'tsm ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/tsm) &&     mkdir -p  /run/systemd/system /opt/tableau/docker_build &&     yum install -y              "https://beta.tableau.com/linux_files/tableau-server-automated-installer-${TABLEAU_VERSION}.noarch.rpm"              "https://beta.tableau.com/linux_files/tableau-server-${TABLEAU_VERSION}.x86_64.rpm"               "https://beta.tableau.com/linux_driver/tableau-postgresql-odbc-9.5.3-1.x86_64.rpm"  &&     rm -rf /var/tmp/yum-*' returned a non-zero code: 1
Makefile:6: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by tfoldi** [comment]
I just pushed a fix for this. It will take the binaries from tableau esd instead of beta site
